odometry_node:
  ros__parameters:
    p0:
      x: 0.0
      y: 0.0
    p1:
      x: 2.0
      y: 2.0
    p2:
      x: 0.0
      y: 4.0
    p3:
      x: 2.0
      y: 6.0
    p4:
      x: 4.0
      y: 1.0